version: "3"
services:
  s_api:
    container_name: c_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7041:7041
    networks:
      - e_commerce

  s_db:
    container_name: c_postgresdb
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgre_db_e_commerce:/var/lib/postgresql/data/pgdata
    networks:
      - e_commerce

volumes:
  postgre_db_e_commerce:

networks:
  e_commerce:
    name: e_commerce
