version: "3"
services:
  s_api:
    container_name: c_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:7041
      - 443:7041
    networks:
      - e_commerce
    environment:
      - "ConnectionStrings:SQLServer=${ConnectionStrings_SQLServer}"
      - "Token:SecurityKey=${Token_SecurityKey}"
      - "Token:Issuer=${Token_Issuer}"
      - "Token:Audience=${Token_Audience}"
      - "Storage:Azure=${Storage_Azure}"
      - "Mail:Username=${Mail_Username}"
      - "Mail:Port=${Mail_Port}"
      - "Mail:Password=${Mail_Password}"
      - "Mail:Host=${Mail_Host}"
      - "Mail:EmailHeader=${Mail_EmailHeader}"
      - "Logging:LogLevel:${Logging_LogLevel}"
      - "Logging:LogLevel:Default=${Logging_LogLevel_Default}"
      - "GoogleCredential=${GoogleCredential}"
      - "BaseStorageUrl=${BaseStorageUrl}"
      - "AngularClientUrl=${AngularClientUrl}"
      - "AllowedHosts=${AllowedHosts}"
      - "Certificate=${Certificate}"

  s_db:
    container_name: c_postgresdb
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgre_db_e_commerce:/var/lib/postgresql/data/pgdata
    networks:
      - e_commerce
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "PGDATA=${PGDATA}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"

volumes:
  postgre_db_e_commerce:

networks:
  e_commerce:
    name: e_commerce
